name: spacetime_test

on:
  push:
  pull_request:
  schedule:
    - cron: '23 17 * * *'

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
          os: [ubuntu-18.04, macos-latest]
          cmake_build_type: [Release, Debug]

        fail-fast: false

    steps:

    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: dependency (ubuntu)
      if: matrix.os != 'macos-latest'
      run: |
        sudo apt-get -qqy update
        sudo apt-get -qy install \
            sudo curl git build-essential make cmake libc6-dev gcc-7 g++-7 \
            python3.7 python3.7-dev python3.7-venv
        sudo rm /usr/bin/python3
        sudo ln -s python3.7 /usr/bin/python3
        sudo pip3 install -U pip
        sudo pip3 install -U setuptools
        sudo pip3 install -U numpy pytest cmake

    - name: dependency (macos)
      if: matrix.os == 'macos-latest'
      run: |
        brew install python3
        pip3 install -U pip
        pip3 install -U setuptools
        pip3 install -U numpy pytest cmake

    - name: dependency (manual)
      run: sudo ${GITHUB_WORKSPACE}/contrib/depend/install.sh everything

    - name: show dependency
      run: |
        echo "gcc path: $(which gcc)"
        echo "gcc version: $(gcc --version)"
        echo "cmake path: $(which cmake)"
        echo "cmake version: $(cmake --version)"
        echo "python3 path: $(which python3)"
        echo "python3 version: $(python3 --version)"
        echo "pip3 path: $(which pip3)"
        python3 -c 'import numpy ; print("numpy.__version__:", numpy.__version__)'
        echo "pytest path: $(which pytest)"
        echo "pytest version: $(pytest --version)"

    - name: buildext
      run: |
        cd ${GITHUB_WORKSPACE}/spacetime
        make buildext \
          VERBOSE=1 \
          CMAKE_BUILD_TYPE=${{ matrix.cmake_build_type }} \
          CMAKE_ARGS="-DPYTHON_EXECUTABLE=$(which python3)"

    - name: gtest
      run: |
        cd ${GITHUB_WORKSPACE}/spacetime
        make gtest \
          VERBOSE=1 \
          CMAKE_BUILD_TYPE=${{ matrix.cmake_build_type }} \
          CMAKE_ARGS="-DPYTHON_EXECUTABLE=$(which python3)"

    - name: pytest
      run: |
        cd ${GITHUB_WORKSPACE}/spacetime
        make pytest \
          VERBOSE=1 \
          CMAKE_BUILD_TYPE=${{ matrix.cmake_build_type }} \
          CMAKE_ARGS="-DPYTHON_EXECUTABLE=$(which python3)"
